[package]
name = "cache-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cache-server-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "cache-server"
path = "src/bin/server.rs"

[dependencies]
bytes = "1.4.0"
clap = "4.3.2"
tokio = { version = "1.28.2", features = ["full"] }
