[package]
name = "cache-server-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.3.2"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
toml = "0.7.5"
serde_yaml = "0.9.22"
